### ISSUE TITLE
ImportError: cannot import name 'CONF_SOLARRAD' from 'homeassistant.components.rainmachine' — breaks integration on HA 2026.8

### ISSUE THREAD

**Issue by patrusco** [goir/ha-solarmanager-ch#15]
### Description

After updating Home Assistant Core from 2026.7.4 to **2026.8.1**, the `solarmanagerch` integration fails to load with a `setup_error`.

### Environment

- Home Assistant Core: 2026.8.1
- Installation type: Home Assistant OS (Supervisor)
- Integration version: latest `main` (commit `6493c28`)

### Traceback

ImportError: cannot import name 'CONF_SOLARRAD' from 'homeassistant.components.rainmachine' (/usr/src/homeassistant/homeassistant/components/rainmachine/init.py)

File "/config/custom_components/solar-manager/coordinator.py", line 6, in <module>
from homeassistant.components.rainmachine import CONF_SOLARRAD

### Root cause

`coordinator.py` line 6 imports `CONF_SOLARRAD` from HA Core's `rainmachine` component. This constant was removed/renamed in HA Core 2026.8. Searching the file, `CONF_SOLARRAD` is **never actually referenced anywhere else** in `coordinator.py` — it appears to be a stray import left over from copy-pasting boilerplate (Solar Manager has no relation to RainMachine).

### Fix

Simply removing (or commenting out) line 6 resolves the issue with no side effects, since the constant is unused:

```python
# from homeassistant.components.rainmachine import CONF_SOLARRAD
```

Confirmed working on my instance — integration loads (`state: loaded`) and all sensors report correctly again after removing this line and reloading the config entry.

### Suggested permanent fix

Please remove this unused import from the codebase so users don't hit this again on future HA Core updates that touch the `rainmachine` component's internals.

**Comment by patrusco** [comment]
Duplicate of #14 — same root cause and fix confirmed working on Home Assistant 2026.8.1.

**Comment by Gugger83** [comment]
It didn't work for me despite commenting it out. Attached are the error messages that are still occurring.

<img width="619" height="210" alt="Image" src="https://github.com/user-attachments/assets/f2632a73-d69f-4040-8435-f95a600c6de3" />
<img width="1281" height="972" alt="Image" src="https://github.com/user-attachments/assets/06a61131-9137-46ed-ad4f-6e8619c2eb13" />
<img width="1316" height="655" alt="Image" src="https://github.com/user-attachments/assets/4b20b47a-e6b4-4d54-8f6c-389c08b5807b" />

**Comment by patrusco** [comment]
Looking at your screenshot — the fix is applied correctly, line 6 is commented out properly and I double-checked, no other file in the repo references CONF_SOLARRAD. That error message is very likely just the old cached log entry from before you edited the file. Try reloading the integration (Settings → Devices & Services → Solar Manager CH → ⋮ → Reload) or restart HA fully, then check if the entry still shows the error or loads fine now.

**Comment by Gugger83** [comment]
Thank you for checking and for your feedback.

I have already tried restarting the device several times, but unfortunately without success. The same error message still appears, and it continues to report a setup/configuration error.

Additionally, the error message still refers to line 27.

Could you please advise on the next steps or suggest an alternative solution?

<img width="1316" height="730" alt="Image" src="https://github.com/user-attachments/assets/7cfe59f0-6ce0-4828-8555-d1a4b0bb62a3" />
<img width="1225" height="1005" alt="Image" src="https://github.com/user-attachments/assets/700ebb9c-c11d-42e8-9146-13eddf9bde62" />
